"use client";
import { SessionProvider } from "next-auth/react";
import AppBar from "./Appbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Cool Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <AppBar />
          <div className="p-10 bg-indigo-100 h-screen">{children}</div>
        </SessionProvider>
      </body>
    </html>
  );
}
