"use client";
import { SessionProvider } from "next-auth/react";
import AppBar from "./Appbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Cool Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  console.log(inter.className);
  return (
    <html lang="en">
      <body
        className={[inter.className, "bg-slate-950 text-white  ')]"].join(" ")}
      >
        <SessionProvider session={session}>
          <AppBar />
          <div className="min-h-screen max-w-7xl mx-auto sm:px-6">
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
